### PR TITLE
pool.js

### PR DESCRIPTION
**Pull request by Jenniphoher**
This is the pool.js without modules folder.

### CODE REVIEW

**Review by mntokijabe — CHANGES_REQUESTED** [review]
the database is not going to be called awesome_reads.  I am naming it koala_holla

**Review by Jenniphoher — COMMENTED** [review]
changed to koala_holla

**Review by mntokijabe — COMMENTED** [review]
looks good!

**Comment by mntokijabe** [comment]
cleared the pool.js file to go

**Pull request merged**
